openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
  version: '1.0'
servers:
  - url: 'http://localhost:4040'
    description: Inferred Url
tags:
  - name: magic-service-controller
    description: Magic Service Controller
paths:
  /magic:
    post:
      tags:
        - magic-service-controller
      summary: getAnswer
      operationId: getAnswerUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MagicAnswers'
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MagicAnswers'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /quote:
    get:
      tags:
        - magic-service-controller
      summary: getQuote
      operationId: getQuoteUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/QuoteofADay'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /word:
    get:
      tags:
        - magic-service-controller
      summary: getWord
      operationId: getWordUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DefinitionOfWords'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    DefinitionOfWords:
      title: DefinitionOfWords
      type: object
      properties:
        definition:
          type: string
        id:
          type: integer
          format: int32
        word:
          type: string
    MagicAnswers:
      title: MagicAnswers
      type: object
      properties:
        answer:
          type: string
        id:
          type: integer
          format: int32
        question:
          type: string
    QuoteofADay:
      title: QuoteofADay
      type: object
      properties:
        author:
          type: string
        id:
          type: integer
          format: int32
        quote:
          type: string
